const ADD_NEW_CAR = "ADD_NEW_CAR";
const CHANGE_ACTIVE_CAR = "CHANGE_ACTIVE_CAR";
const START_ADD_NEW_CARD = "START_ADD_NEW_CARD";

export {
    ADD_NEW_CAR,
    CHANGE_ACTIVE_CAR,
    START_ADD_NEW_CARD,
}