/**ACCESSORY */
export const ADD_ACCESSORY = "ADD_ACCESSORY";
export const CHANGE_ACCESSORY = "CHANGE_ACCESSORY";
export const TOGGLE_ACCESSORY_STATUS = "TOGGLE_ACCESSORY_STATUS";

/**TASK */
export const ADD_TASK = "ADD_TASK";
export const TOGGLE_COMPLITE_TASK = "TOGGLE_COMPLITE_TASK";
export const MOVE_TO_DELETED = "MOVE_TO_DELETED";
export const DELETE_TASK = "DELETE_TASK";
export const MOVE_TO_ACTIVE = "MOVE_TO_ACTIVE";

/**CAR */
export const ADD_CAR = "ADD_CAR";
export const DELETE_CAR = "DELETE_CAR";

/**SETTINGS */
export const CHANGE_ACTIVE_CAR = "CHANGE_ACTIVE_CAR";
export const CHANGE_FILTER = "CHANGE_FILTER";
