const ADD_NEW_CAR = "ADD_NEW_CAR";
const CHANGE_ACTIVE_CAR = "CHANGE_ACTIVE_CAR";
const START_ADD_NEW_CARD = "START_ADD_NEW_CARD";
const TOGGLE_ACCESSORIES = "TOGGLE_ACCESSORIES";
const CHANGE_FILTER = 'CHANGE_FILTER';
const ADD_NEW_TASK = 'ADD_NEW_TASK';
const COMPLITE_TASK = "COMPLITE_TASK";

export {
    ADD_NEW_CAR,
    CHANGE_ACTIVE_CAR,
    START_ADD_NEW_CARD,
    TOGGLE_ACCESSORIES,
    CHANGE_FILTER,
    ADD_NEW_TASK,
    COMPLITE_TASK,
}